const studentActionTypes = {
    REGISTER_REQUEST: "STUDENT_REGISTER_REQUEST",
    REGISTER_SUCCESS: "STUDENT_REGISTER_SUCCESS",
    REGISTER_FAILURE: "STUDENT_REGISTER_FAILURE",

    LOGIN_REQUEST: "STUDENT_LOGIN_REQUEST",
    LOGIN_SUCCESS: "STUDENT_LOGIN_SUCCESS",
    LOGIN_FAILURE: "STUDENT_LOGIN_FAILURE",

    LOGOUT_REQUEST: "STUDENT_LOGOUT_REQUEST",
    LOGOUT_SUCCESS: "STUDENT_LOGOUT_SUCCESS",
    LOGOUT_FAILURE: "STUDENT_LOGOUT_FAILURE",

    CV_REQUEST: "UPLOAD_CV_REQUEST",
    CV_SUCCESS: "UPLOAD_CV_SUCCESS",
    CV_FAILURE: "UPLOAD_CV_FAILURE",

    APPLY_PROJECT_REQUEST: "APPLY_PROJECT_REQUEST",
    APPLY_PROJECT_SUCCESS: "APPLY_PROJECT_SUCCESS",
    APPLY_PROJECT_FAILURE: "APPLY_PROJECT_FAILURE",

    UPDATE_STUDENT_REQUEST: "UPDATE_STUDENT_REQUEST",
    UPDATE_STUDENT_SUCCESS: "UPDATE_STUDENT_SUCCESS",
    UPDATE_STUDENT_FAILURE: "UPDATE_STUDENT_FAILURE",

    UPDATE_PASSWORD_REQUEST: "UPDATE_PASSWORD_REQUEST",
    UPDATE_PASSWORD_SUCCESS: "UPDATE_PASSWORD_SUCCESS",
    UPDATE_PASSWORD_FAILURE: "UPDATE_PASSWORD_FAILURE",

    AVATAR_REQUEST: "UPDATE_AVATAR_REQUEST",
    AVATAR_SUCCESS: "UPDATE_AVATAR_SUCCESS",
    AVATAR_FAILURE: "UPDATE_AVATAR_FAILURE",
};

export default studentActionTypes;
