const projectActionTypes = {
    FETCH_PROJECTS_REQUEST: "FETCH_PROJECTS_REQUEST",
    FETCH_PROJECTS_SUCCESS: "FETCH_PROJECTS_SUCCESS",
    FETCH_PROJECTS_FAILURE: "FETCH_PROJECTS_FAILURE",

    UPDATE_PROJECT_REQUEST: "UPDATE_PROJECT_REQUEST",
    UPDATE_PROJECT_SUCCESS: "UPDATE_PROJECT_SUCCESS",
    UPDATE_PROJECT_FAILURE: "UPDATE_PROJECT_FAILURE",
};

export default projectActionTypes;