const mentorActionTypes = {
    LOGIN_REQUEST: "MENTOR_LOGIN_REQUEST",
    LOGIN_SUCCESS: "MENTOR_LOGIN_SUCCESS",
    LOGIN_FAILURE: "MENTOR_LOGIN_FAILURE",

    LOGOUT_REQUEST: "MENTOR_LOGOUT_REQUEST",
    LOGOUT_SUCCESS: "MENTOR_LOGOUT_SUCCESS",
    LOGOUT_FAILURE: "MENTOR_LOGOUT_FAILURE",

    SELECT_STUDENT_REQUEST: "SELECT_STUDENT_REQUEST",
    SELECT_STUDENT_SUCCESS: "SELECT_STUDENT_SUCCESS",
    SELECT_STUDENT_FAILURE: "SELECT_STUDENT_FAILURE",

    SHORTLIST_STUDENT_REQUEST: "SHORTLIST_STUDENT_REQUEST",
    SHORTLIST_STUDENT_SUCCESS: "SHORTLIST_STUDENT_SUCCESS",
    SHORTLIST_STUDENT_FAILURE: "SHORTLIST_STUDENT_FAILURE",

    GET_STUDENTS_REQUEST: "GET_STUDENTS_REQUEST",
    GET_STUDENTS_SUCCESS: "GET_STUDENTS_SUCCESS",
    GET_STUDENTS_FAILURE: "GET_STUDENTS_FAILURE",

    UPDATE_PASSWORD_REQUEST: "UPDATE_PASSWORD_REQUEST",
    UPDATE_PASSWORD_SUCCESS: "UPDATE_PASSWORD_SUCCESS",
    UPDATE_PASSWORD_FAILURE: "UPDATE_PASSWORD_FAILURE",

    AVATAR_REQUEST: "AVATAR_REQUEST",
    AVATAR_SUCCESS: "AVATAR_SUCCESS",
    AVATAR_FAILURE: "AVATAR_FAILURE",

    GET_AVATAR_REQUEST: "GET_AVATAR_REQUEST",
    GET_AVATAR_SUCCESS: "GET_AVATAR_SUCCESS",
    GET_AVATAR_FAILURE: "GET_AVATAR_FAILURE"
};
export default mentorActionTypes;
